spring:
  datasource:
    url: jdbc:mysql://35.240.237.237:3306/product_db
    username: admin
    password: admin
  data:
    redis:
      host: localhost
      port: 6739
      username: admin
      password: admin
eureka:
  client:
    enabled: false
  instance:
    hostname: localhost