spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: admin
    password: admin
  data:
    redis:
      url: redis://localhost:6379
eureka:
  client:
    enabled: false
  instance:
    hostname: localhost