-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 01:00:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema product_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema product_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `product_service`;
USE `product_service`;

-- -----------------------------------------------------
-- Table `product_service`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.user
(
    `id` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_service`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.product
(
    `id`          VARCHAR(36)                          NOT NULL,
    `is_used`     BIT(1)                               NOT NULL,
    `name`        VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description` TEXT CHARACTER SET 'utf8mb4'         NULL,
    `created_at`  DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `version`     BIGINT UNSIGNED                      NOT NULL,
    `USER_id`     VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_PRODUCT_USER1`
        FOREIGN KEY (`USER_id`)
            REFERENCES `product_service`.user (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_USER1_idx` ON `product_service`.product (`USER_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`PRODUCT_VERSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.product_version
(
    `id`         VARCHAR(36)        NOT NULL,
    `name`       VARCHAR(255)       NOT NULL,
    `is_used`    BIT(1)             NOT NULL,
    `created_at` DATETIME           NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME           NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `PRODUCT_id` VARCHAR(36)        NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_MODULE_VERSION_MODULE0`
        FOREIGN KEY (`PRODUCT_id`)
            REFERENCES `product_service`.product (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_MODULE_VERSION_MODULE_idx` ON `product_service`.product_version (`PRODUCT_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module
(
    `id`                 VARCHAR(36)                          NOT NULL,
    `is_used`            BIT(1)                               NOT NULL,
    `name`               VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description`        TEXT CHARACTER SET 'utf8mb4'         NULL,
    `created_at`         DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`         DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `version`            BIGINT UNSIGNED                      NOT NULL,
    `PRODUCT_VERSION_id` VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_MODULE_PRODUCT_VERSION1`
        FOREIGN KEY (`PRODUCT_VERSION_id`)
            REFERENCES `product_service`.product_version (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_MODULE_PRODUCT_VERSION1_idx` ON `product_service`.module (`PRODUCT_VERSION_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_VERSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_version
(
    `id`         VARCHAR(36)                          NOT NULL,
    `is_used`    BIT(1)                               NOT NULL,
    `name`       VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
    `created_at` DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `MODULE_id`  VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_MODULE_VERSION_MODULE`
        FOREIGN KEY (`MODULE_id`)
            REFERENCES `product_service`.module (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_MODULE_VERSION_MODULE_idx` ON `product_service`.module_version (`MODULE_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`INSTANCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.instance
(
    `id`                VARCHAR(36)                          NOT NULL,
    `is_used`           BIT(1)                               NOT NULL,
    `name`              VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description`       VARCHAR(255) CHARACTER SET 'utf8mb4' NULL,
    `version`           BIGINT UNSIGNED                      NOT NULL,
    `created_at`        DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `MODULE_VERSION_id` VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_INSTANCE_MODULE_VERSION1`
        FOREIGN KEY (`MODULE_VERSION_id`)
            REFERENCES `product_service`.module_version (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_INSTANCE_MODULE_VERSION1_idx` ON `product_service`.instance (`MODULE_VERSION_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_CHANGELOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_changelog
(
    `id`                VARCHAR(36)                          NOT NULL,
    `title`             VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description`       TEXT CHARACTER SET 'utf8mb4'         NULL,
    `created_at`        DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `MODULE_VERSION_id` VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_MODULE_CHANGELOG_MODULE_VERSION1`
        FOREIGN KEY (`MODULE_VERSION_id`)
            REFERENCES `product_service`.module_version (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_MODULE_CHANGELOG_MODULE_VERSION1_idx` ON `product_service`.module_changelog (`MODULE_VERSION_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`INSTANCE_ATTRIBUTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.instance_attribute
(
    `id`          VARCHAR(36)                          NOT NULL,
    `num_order`   TINYINT UNSIGNED                     NOT NULL,
    `key`         VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `value`       VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
    `INSTANCE_id` VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_INSTANCE_ATTRIBUTE_INSTANCE1`
        FOREIGN KEY (`INSTANCE_id`)
            REFERENCES `product_service`.instance (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_INSTANCE_ATTRIBUTE_INSTANCE1_idx` ON `product_service`.instance_attribute (`INSTANCE_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`PRODUCT_CHANGELOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.product_changelog
(
    `id`                 VARCHAR(36)                          NOT NULL,
    `title`              VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description`        TEXT CHARACTER SET 'utf8mb4'         NULL,
    `created_at`         DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`         DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `PRODUCT_VERSION_id` VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_PRODUCT_CHANGELOG_PRODUCT_VERSION1`
        FOREIGN KEY (`PRODUCT_VERSION_id`)
            REFERENCES `product_service`.product_version (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_CHANGELOG_PRODUCT_VERSION1_idx` ON `product_service`.product_changelog (`PRODUCT_VERSION_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.attachment
(
    `id`      VARCHAR(36) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_service`.`PRODUCT_CHANGELOG_has_ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.product_changelog_has_attachment
(
    `PRODUCT_CHANGELOG_id` VARCHAR(36) NOT NULL,
    `ATTACHMENT_id`        VARCHAR(36) NOT NULL,
    `created_at`           DATETIME    NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`PRODUCT_CHANGELOG_id`, `ATTACHMENT_id`),
    CONSTRAINT `fk_PRODUCT_CHANGELOG_ATTACHMENT_ATTACHMENT1`
        FOREIGN KEY (`ATTACHMENT_id`)
            REFERENCES `product_service`.attachment (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_PRODUCT_CHANGELOG_has_ATTACHMENT_PRODUCT_CHANGELOG1`
        FOREIGN KEY (`PRODUCT_CHANGELOG_id`)
            REFERENCES `product_service`.product_changelog (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_CHANGELOG_ATTACHMENT_ATTACHMENT1_idx` ON `product_service`.product_changelog_has_attachment (`ATTACHMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_PRODUCT_CHANGELOG_has_ATTACHMENT_PRODUCT_CHANGELOG1_idx` ON `product_service`.product_changelog_has_attachment (`PRODUCT_CHANGELOG_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_CHANGELOG_has_ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_changelog_has_attachment
(
    `ATTACHMENT_id`       VARCHAR(36) NOT NULL,
    `MODULE_CHANGELOG_id` VARCHAR(36) NOT NULL,
    `created_at`          DATETIME    NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ATTACHMENT_id`, `MODULE_CHANGELOG_id`),
    CONSTRAINT `fk_PRODUCT_CHANGELOG_ATTACHMENT_ATTACHMENT10`
        FOREIGN KEY (`ATTACHMENT_id`)
            REFERENCES `product_service`.attachment (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_MODULE_CHANGELOG_has_ATTACHMENT_MODULE_CHANGELOG1`
        FOREIGN KEY (`MODULE_CHANGELOG_id`)
            REFERENCES `product_service`.module_changelog (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_CHANGELOG_ATTACHMENT_ATTACHMENT1_idx` ON `product_service`.module_changelog_has_attachment (`ATTACHMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_MODULE_CHANGELOG_has_ATTACHMENT_MODULE_CHANGELOG1_idx` ON `product_service`.module_changelog_has_attachment (`MODULE_CHANGELOG_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`PRODUCT_DOCUMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.product_document
(
    `id`          VARCHAR(36)                          NOT NULL,
    `title`       VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL,
    `created_at`  DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `PRODUCT_id`  VARCHAR(36)                          NULL,
    `USER_id`     VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_PRODUCT_DOCUMENT_PRODUCT1`
        FOREIGN KEY (`PRODUCT_id`)
            REFERENCES `product_service`.product (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_PRODUCT_DOCUMENT_USER1`
        FOREIGN KEY (`USER_id`)
            REFERENCES `product_service`.user (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_DOCUMENT_PRODUCT1_idx` ON `product_service`.product_document (`PRODUCT_id` ASC) VISIBLE;

CREATE INDEX `fk_PRODUCT_DOCUMENT_USER1_idx` ON `product_service`.product_document (`USER_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`PRODUCT_DOCUMENT_has_ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.product_document_has_attachment
(
    `DOCUMENT_id`   VARCHAR(36) NOT NULL,
    `ATTACHMENT_id` VARCHAR(36) NOT NULL,
    `created_at`    DATETIME    NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`DOCUMENT_id`, `ATTACHMENT_id`),
    CONSTRAINT `fk_PRODUCT_DOCUMENT_has_ATTACHMENT_PRODUCT_DOCUMENT1`
        FOREIGN KEY (`DOCUMENT_id`)
            REFERENCES `product_service`.product_document (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_PRODUCT_DOCUMENT_has_ATTACHMENT_ATTACHMENT1`
        FOREIGN KEY (`ATTACHMENT_id`)
            REFERENCES `product_service`.attachment (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_DOCUMENT_has_ATTACHMENT_ATTACHMENT1_idx` ON `product_service`.product_document_has_attachment (`ATTACHMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_PRODUCT_DOCUMENT_has_ATTACHMENT_PRODUCT_DOCUMENT1_idx` ON `product_service`.product_document_has_attachment (`DOCUMENT_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_DOCUMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_document
(
    `id`          VARCHAR(36)                          NOT NULL,
    `title`       VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL,
    `created_at`  DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `MODULE_id`   VARCHAR(36)                          NULL,
    `USER_id`     VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_MODULE_DOCUMENT_MODULE1`
        FOREIGN KEY (`MODULE_id`)
            REFERENCES `product_service`.module (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_MODULE_DOCUMENT_USER1`
        FOREIGN KEY (`USER_id`)
            REFERENCES `product_service`.user (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_MODULE_DOCUMENT_MODULE1_idx` ON `product_service`.module_document (`MODULE_id` ASC) VISIBLE;

CREATE INDEX `fk_MODULE_DOCUMENT_USER1_idx` ON `product_service`.module_document (`USER_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`DOCUMENT_LABEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.document_label
(
    `id`          VARCHAR(36)                          NOT NULL,
    `name`        VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
    `description` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL,
    `created_at`  DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `color`       VARCHAR(6)                           NOT NULL COMMENT 'Color code in HEX (6 characters)',
    `USER_id`     VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_LABEL_USER1`
        FOREIGN KEY (`USER_id`)
            REFERENCES `product_service`.user (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);

CREATE INDEX `fk_LABEL_USER1_idx` ON `product_service`.document_label (`USER_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_DOCUMENT_has_DOCUMENT_LABEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_document_has_document_label
(
    `DOCUMENT_id` VARCHAR(36)      NOT NULL,
    `LABEL_id`    VARCHAR(36)      NOT NULL,
    `num_order`   TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (`DOCUMENT_id`, `LABEL_id`),
    CONSTRAINT `fk_MODULE_DOCUMENT_has_LABEL_MODULE_DOCUMENT1`
        FOREIGN KEY (`DOCUMENT_id`)
            REFERENCES `product_service`.module_document (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_MODULE_DOCUMENT_has_DOCUMENT_LABEL_DOCUMENT_LABEL1`
        FOREIGN KEY (`LABEL_id`)
            REFERENCES `product_service`.document_label (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_MODULE_DOCUMENT_has_LABEL_MODULE_DOCUMENT1_idx` ON `product_service`.module_document_has_document_label (`DOCUMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_MODULE_DOCUMENT_has_DOCUMENT_LABEL_LABEL1_idx` ON `product_service`.module_document_has_document_label (`LABEL_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`PRODUCT_DOCUMENT_has_DOCUMENT_LABEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.product_document_has_document_label
(
    `DOCUMENT_id` VARCHAR(36)      NOT NULL,
    `LABEL_id`    VARCHAR(36)      NOT NULL,
    `num_order`   TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (`DOCUMENT_id`, `LABEL_id`),
    CONSTRAINT `fk_PRODUCT_DOCUMENT_has_LABEL_PRODUCT_DOCUMENT1`
        FOREIGN KEY (`DOCUMENT_id`)
            REFERENCES `product_service`.product_document (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_PRODUCT_DOCUMENT_has_DOCUMENT_LABEL_DOCUMENT_LABEL1`
        FOREIGN KEY (`LABEL_id`)
            REFERENCES `product_service`.document_label (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_DOCUMENT_has_LABEL_PRODUCT_DOCUMENT1_idx` ON `product_service`.product_document_has_document_label (`DOCUMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_PRODUCT_DOCUMENT_has_DOCUMENT_LABEL_LABEL1_idx` ON `product_service`.product_document_has_document_label (`LABEL_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_DEPLOYING_DOCUMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_deploying_document
(
    `id`                VARCHAR(36)                          NOT NULL,
    `name`              VARCHAR(150) CHARACTER SET 'utf8mb4' NOT NULL,
    `description`       VARCHAR(255) CHARACTER SET 'utf8mb4' NULL,
    `created_at`        DATETIME                             NULL,
    `updated_at`        DATETIME                             NULL,
    `USER_id`           VARCHAR(36)                          NOT NULL,
    `MODULE_VERSION_id` VARCHAR(36)                          NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_DEPLOYING_MODULE_DOCUMENT_USER1`
        FOREIGN KEY (`USER_id`)
            REFERENCES `product_service`.user (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_MODULE_DEPLOYING_DOCUMENT_MODULE_VERSION1`
        FOREIGN KEY (`MODULE_VERSION_id`)
            REFERENCES `product_service`.module_version (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);

CREATE INDEX `fk_MODULE_DEPLOYING_DOCUMENT_USER1_idx` ON `product_service`.module_deploying_document (`USER_id` ASC) INVISIBLE;

CREATE INDEX `fk_MODULE_DEPLOYING_DOCUMENT_MODULE_VERSION1_idx` ON `product_service`.module_deploying_document (`MODULE_VERSION_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_DEPLOYING_DOCUMENT_has_ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_deploying_document_has_attachment
(
    `DOCUMENT_id`   VARCHAR(36) NOT NULL,
    `ATTACHMENT_id` VARCHAR(36) NOT NULL,
    `created_at`    DATETIME    NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`DOCUMENT_id`, `ATTACHMENT_id`),
    CONSTRAINT `fk_DEPLOYING_MODULE_DOCUMENT_has_ATTACHMENT_DEPLOYING_MODULE_1`
        FOREIGN KEY (`DOCUMENT_id`)
            REFERENCES `product_service`.module_deploying_document (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_DEPLOYING_MODULE_DOCUMENT_has_ATTACHMENT_ATTACHMENT1`
        FOREIGN KEY (`ATTACHMENT_id`)
            REFERENCES `product_service`.attachment (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);

CREATE INDEX `fk_MODULE_DEPLOYING_DOCUMENT_has_ATTACHMENT_ATTACHMENT1_idx` ON `product_service`.module_deploying_document_has_attachment (`ATTACHMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_MODULE_DEPLOYING_DOCUMENT_has_ATTACHMENT_DOCUMENT1_idx` ON `product_service`.module_deploying_document_has_attachment (`DOCUMENT_id` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `product_service`.`MODULE_DOCUMENT_has_ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_service`.module_document_has_attachment
(
    `DOCUMENT_id`   VARCHAR(36) NOT NULL,
    `ATTACHMENT_id` VARCHAR(36) NOT NULL,
    `created_at`    DATETIME    NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`DOCUMENT_id`, `ATTACHMENT_id`),
    CONSTRAINT `fk_MODULE_DOCUMENT_has_ATTACHMENT_MODULE_DOCUMENT1`
        FOREIGN KEY (`DOCUMENT_id`)
            REFERENCES `product_service`.module_document (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_MODULE_DOCUMENT_has_ATTACHMENT_ATTACHMENT1`
        FOREIGN KEY (`ATTACHMENT_id`)
            REFERENCES `product_service`.attachment (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_MODULE_DOCUMENT_has_ATTACHMENT_ATTACHMENT1_idx` ON `product_service`.module_document_has_attachment (`ATTACHMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_MODULE_DOCUMENT_has_ATTACHMENT_MODULE_DOCUMENT1_idx` ON `product_service`.module_document_has_attachment (`DOCUMENT_id` ASC) VISIBLE;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
